//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaraokeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public string MaPhieuNhap { get; set; }
        public string MaDichVu { get; set; }
        public Nullable<int> DonGiaMua { get; set; }
        public Nullable<int> SoLuongMua { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
